### PR TITLE
Bug 1038618 - [testing] Test that one time tasks are marked completed on...

### PR DESCRIPTION
**Pull request by bitgeeky**
The test works fine on merging https://github.com/mozilla/oneanddone/pull/163

### CODE REVIEW

**Comment by rbillings** [comment]
@bitgeeky - I know it's been a long time, but if you get a chance it would be good to finish this up, or we'll start from scratch.

**Comment by bitgeeky** [comment]
Hey @rbillings  yeah its been a long time indeed ! 
I have never said No to Web QA work :P continuing the legacy, I'll get in touch with @bobsilverberg  and try to get the pulls merged.

I will need a bit of time to set-up my dev env and get things up and running, and review everything again.
It should not take more than a week, will that be fine ?
Thanks :-)

**Comment by rbillings** [comment]
Yes, that works - I believe PR reviews will be delayed due to other project work so take your time. I'm glad to hear you're working on this!

**Comment by bobsilverberg** [comment]
We are no longer going to add any tests to this repo which require that data be populated via the API, so I am going to close this.

**Pull request closed without merging**
