### PR TITLE
one and done #41 - test task detail page

### PR DESCRIPTION
**Pull request by dabiid**
one and done task 41 - test task detail page

Notes: waiting on changes for issue #46 to incorporate new Tasks model and combine the HomePage.suggested_tasks property (I'm too n00b to feel like merging the changes from her fork into my own). I'm also curious about naming tests and file structure - let me know if I should change anything there or if there's a guide that I missed.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@dabiid Thanks for taking this on. I haven't looked at the code yet as you indicated that you were awaiting the merge of PR #46 before finalizing your code. That has now been merged, so please feel free to pull those changes in.

Another suggestion I would make is that you do your work in a feature branch, rather than your master branch. You will find that will save headaches in the future. Let me know if you need any help with that.

Please ping me by adding a comment here once you've been able to pull in the new changes and update your pull request. If you do need some help with that I can be found on IRC in our team channel which is #mozwebqa at irc.mozilla.org and/or you can send email to our mailing list, info for which can be found at https://mail.mozilla.org/listinfo/mozwebqa.

Thanks again for taking this on and I look forward to working with you. :)

**Comment by dabiid** [comment]
Alright, I merged the changes and it seems to be working. 

What's the correct way to use git (I've only used svn). I created a branch for my second change but then merged it in to my master before this pull request was completed (probably a mistake). Should I have created two feature branches? I'm not exactly sure when to merge my branch and master and when to request a pull to the original. Thanks for your help and suggestions.

**Comment by bobsilverberg** [comment]
@dabiid git is very different from svn so you will probably find that you have to forget everything you know about svn in order to work well with git. It's a whole different world!

It might be best if you do a bit of introductory reading/learning about Git which will make working with it much easier in the future. A couple of resources to check out are https://try.github.io/ and rogerdudler.github.io/git-guide/. I can suggest some steps for you to take with this PR for now, but I do think you'll find it easier if you read up a bit. For now, I would suggest doing the following:

1. Make a copy of the folder in which you have your current oneanddone-tests git repository. You're going to want to create a brand new git repo, so an easy way to save all of the work you've done thus far is to just copy the whole folder. Let's assume you call that new folder `oneanddone-tests-copy`.
2. When working with forks and git you generally want to keep your own `master` branch clean and in sync with the master branch on the main repo (the one you forked). You do this by working in a feature branch instead of `master`. Your `master` branch is kind of messed up now with all of those merge commits, so you want to start clean. For this reason you should:
a. Delete your fork of the `oneanddone-tests` repo and create a brand new one. The `master` branch in your fork also contains all those extra commits.
b. Delete your local `oneanddone-tests` folder and make a new clone of your fork. Make sure to save a copy of your work in another folder, as mentioned in #1 above.
3. You should now have a clean copy of the `oneanddone-tests` repo on your local machine which is exactly the same as the one you originally forked (https://github.com/mozilla/oneanddone-tests). Create a new feature branch in your local repo via the following command:
`git branch -b issue41`
4. You are now working in a new branch called `issue41`. Copy all of the files that were changed (the 4 files that appear in the diff for this PR) from your saved location (which we called `oneanddone-tests-copy) into the folder than contains your current repo. That will put the files in the `issue41` branch.
5. Make sure the new files and included in the commit by using `git add`.
6. Create a new commit using `git commit`. If you do `git log` you should see a single commit added to your repo.
7. Push this feature branch to your fork via `git push origin issue41`
8. Open a new pull request which asks for your `issue41` branch to be merged into the `master` branch of https://github.com/mozilla/oneanddone-tests.

At this point you should have a clean local repo, with your `master` branch the same as the `master` branch of https://github.com/mozilla/oneanddone-tests, and your `issue41` branch containing your changes. That will make everything easier going forward.

One last thing: It would be better if each issue (#41 and #42) were addressed in a separate pull request, which is also why I suggested doing them one at a time. So when you follow the instructions above, please only include the changes required for issue #41 in your `issue41` branch.

I know this is a lot of information. If you have any questions or run into any problems, feel free to visit us in #mozwebqa on irc.mozilla.org or add a comment here.

Good luck!

**Comment by bobsilverberg** [comment]
@dabiid To directly answer your questions about branches and when to merge, the general rule, when working with GitHub forks is to never merge your changes directly into your master branch. You make all of your changes in feature branches and request a merge via a pull request. We will merge the changes into our master branch, and then you can pull the changes down from our repo into your own master branch. That way your master branch is always identical to our master branch, which is what you want.

**Comment by dabiid** [comment]
Great, that really helps. Thanks for all the information. I'll clean up my master and create two new branches and request pulls for each. Hopefully it doesn't take too long... at least I find I learn well when I make mistakes.

**Pull request closed without merging**
