### PR TITLE
One and done #42 - test team details page

### PR DESCRIPTION
**Pull request by dabiid**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@dabiid Thanks for this PR as well. I'm going to hold off reviewing this until we're done with PR #49 as you'll probably want to incorporate changes from that into this one.

**Comment by bobsilverberg** [comment]
@dabiid Unfortunately because some other code has been merged since you created this, it needs to be updated with the latest code from `master`. Please follow the instructions that I gave in PR #49 [1] to update this PR. You may also want to compare the final version of the code in your last commit [2] with this to see if it has any issues. Once that's done please ping me here and I'll take a look.

[1] https://github.com/mozilla/oneanddone-tests/pull/49#issuecomment-159939801
[2] https://github.com/mozilla/oneanddone-tests/commit/e7d83c9994a47b4a9e7f358452c7726fb340e2a4

**Comment by dabiid** [comment]
@bobsilverberg I updated the branch with changes from master. I think I already had the changes since I used cherry-pick to get my branch changes here before adding the second commit but I didn't expect that to be okay in the long run (figured I'd have to pull the master changes and rebase after that pr committed).

**Comment by bobsilverberg** [comment]
This looks good, @dabiid. Sorry to take so long to review it, but we were all away last week.

Thanks for all of your hard work on this and the other PR as well. Great job!

**Pull request merged**
